sudo: false
language: bash
os:
  - linux

git:
  depth: false

stages:
  - build

jobs:
  include:

    - name: "Build Arduino 0"
      if: tag IS blank AND (type = pull_request OR (type = push AND branch = master))
      stage: build
      script: $TRAVIS_BUILD_DIR/travis/run-examples.sh 0 5

    - name: "Build Arduino 1"
      if: tag IS blank AND (type = pull_request OR (type = push AND branch = master))
      stage: build
      script: $TRAVIS_BUILD_DIR/travis/run-examples.sh 1 5

    - name: "Build Arduino 2"
      if: tag IS blank AND (type = pull_request OR (type = push AND branch = master))
      stage: build
      script: $TRAVIS_BUILD_DIR/travis/run-examples.sh 2 5

    - name: "Build Arduino 3"
      if: tag IS blank AND (type = pull_request OR (type = push AND branch = master))
      stage: build
      script: $TRAVIS_BUILD_DIR/travis/run-examples.sh 3 5

    - name: "Build Arduino 4"
      if: tag IS blank AND (type = pull_request OR (type = push AND branch = master))
      stage: build
      script: $TRAVIS_BUILD_DIR/travis/run-examples.sh 4 5

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/46eabf7ad1d622bcd8cc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
