#!/bin/bash

DESTBIN="/usr/local/bin/arduino-sketch"
if [ -f "$DESTBIN" ]; then
  
  PIDS=`ps ax | grep telnet | grep -v grep | awk '{print $1}'`
  for pid in $PIDS; do
    echo "KILLING: $pid"
    kill -9 $pid > /dev/null 2>&1
    sleep 1
  done
  
  killall arduino-sketch > /dev/null 2>&1
  cd /
  $DESTBIN >> /run/sketch.log 2>&1 &
else
  exit 1;
fi
