#!/bin/bash
#called by Arduino IDE usually to upload the HEX to the MCU
#here we use it to start the sketch
LOGFILE="/run/sketch.log"
SKETCH="/tmp/sketch.bin"

BINNAME="arduino-sketch"
DESTBIN="/usr/local/bin/$BINNAME"


PIDS=`ps ax | grep telnet | grep -v grep | awk '{print $1}'`
for pid in $PIDS; do
  echo "KILLING: $pid"
  kill -9 $pid > /dev/null 2>&1
  sleep 1
done

killall $BINNAME > /dev/null 2>&1
mv $SKETCH $DESTBIN
cd /
$DESTBIN >> $LOGFILE 2>&1 &

echo "Sketch Started"
